Added some features and contribute section
devXprite/gitglance pull request #20
Opened 2024-05-11 15:05 UTC by Varda003

added new features to the about project in the file. changed the alignment.. Also added about how to contribute in this project. Last added support section as well
#9

2024-05-11 15:10 UTC, Varda003 commented
HI @devXprite  Please merge my pull request

2024-05-12 09:29 UTC, Varda003 commented
Please @devXprite  merge my pull request

2024-05-12 10:18 UTC, devXprite requested changes

2024-05-12 10:18 UTC, devXprite commented on README.md
> +# 1. Fork the Repository
I think these headings are too big. They would be better suited as bullet points instead.

![Screenshot at 2024-05-12 15-43-04](https://github.com/devXprite/gitglance/assets/80192140/dc98c73d-9b1f-4f28-b5aa-0c10467c5e2c)

2024-05-12 10:18 UTC, devXprite commented on README.md
> +
I think there is something wrong. Please fix it.

![Screenshot at 2024-05-12 15-46-03](https://github.com/devXprite/gitglance/assets/80192140/18c3d75f-b0ee-41e4-9944-999bb279ba24)

2024-05-12 10:31 UTC, Varda003 commented
Okay working on it. Will change that

2024-05-12 11:38 UTC, Varda003 commented
Hello @devXprite  Check I have made all the changes as you wanted it looks much better  now please review it accept the pull request

2024-05-12 16:24 UTC, devXprite approved these changes

2024-05-12 16:25 UTC, devXprite commented
> Hello @devXprite Check I have made all the changes as you wanted it looks much better now please review it accept the pull request

Thanks @Varda003. Now it's looking great 👍

2024-05-12 16:25 UTC, merged